# Generated by Django 5.1.1 on 2024-10-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del actor')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido del actor')),
                ('edad', models.IntegerField(verbose_name='Edad del actor')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
                'db_table': 'actor',
            },
        ),
    ]
