# Generated by Django 5.1.1 on 2024-10-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asiento', '0001_initial'),
        ('obra', '0002_obra_actores_delete_detalle_obra_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la reserva')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pago realizado')),
                ('asientos', models.ManyToManyField(related_name='reservas', to='asiento.asiento', verbose_name='Asientos reservados')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
    ]
