# Generated by Django 5.1.2 on 2024-11-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiento', '0002_remove_asiento_disponible_remove_asiento_fila_and_more'),
        ('reserva', '0002_reserva_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='asientos',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la reserva'),
        ),
        migrations.CreateModel(
            name='ReservaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del Asiento en la Reserva')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_asientos', to='asiento.asiento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_asientos', to='reserva.reserva')),
            ],
            options={
                'verbose_name': 'Reserva Asiento',
                'verbose_name_plural': 'Reservas Asientos',
                'db_table': 'reserva_asiento',
                'unique_together': {('reserva', 'asiento')},
            },
        ),
    ]
