# Generated by Django 5.1.2 on 2024-11-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0003_alter_funcion_obra'),
        ('reserva', '0003_remove_reserva_asientos_alter_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='obra',
        ),
        migrations.AddField(
            model_name='reserva',
            name='funcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funciones.funcion', verbose_name='Funcion'),
        ),
    ]
