# Generated by Django 5.1.2 on 2024-11-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_remove_reserva_obra_reserva_funcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pagado',
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='Reservado', max_length=20, verbose_name='Estado reserva'),
            preserve_default=False,
        ),
    ]
