# Generated by Django 5.1.2 on 2024-11-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0001_initial'),
        ('obra', '0008_remove_obra_funcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='obra.obra', verbose_name='Obra'),
        ),
    ]
