# Generated by Django 5.1.2 on 2024-11-04 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0002_funcion_obra'),
        ('obra', '0009_obra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='obra.obra', verbose_name='obra'),
        ),
    ]
