# Generated by Django 5.1.2 on 2024-11-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de Categoria'),
        ),
    ]
