# Generated by Django 5.1.2 on 2024-11-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=20, verbose_name='Nombre de Categoria'),
        ),
    ]
