# Generated by Django 5.1.1 on 2024-10-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_usuario_usuario_email_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
