# Generated by Django 5.1.1 on 2024-10-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.CharField(max_length=5, verbose_name='Número de asiento')),
                ('fila', models.CharField(max_length=2, verbose_name='Fila del asiento')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='obra.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'db_table': 'asiento',
            },
        ),
    ]
