# Generated by Django 5.1.2 on 2024-11-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='fila',
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='obra',
        ),
    ]
