# Generated by Django 5.1.1 on 2024-10-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la obra')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(verbose_name='Hora de la obra')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obras/', verbose_name='Imagen de la obra')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obra',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Obra_actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actores.actores')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.obra')),
            ],
        ),
    ]
