# Generated by Django 5.1.1 on 2024-10-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores', '0001_initial'),
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='actores',
            field=models.ManyToManyField(related_name='obras', to='actores.actores', verbose_name='Actores en la obra'),
        ),
        migrations.DeleteModel(
            name='Detalle_Obra_actor',
        ),
    ]
