# Generated by Django 5.1.2 on 2024-11-04 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores', '0001_initial'),
        ('funciones', '0001_initial'),
        ('obra', '0002_obra_actores_delete_detalle_obra_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='funcion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='funciones.funcion', verbose_name='Obra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra',
            name='actores',
            field=models.ManyToManyField(blank=True, related_name='obras', to='actores.actores', verbose_name='Actores en la obra'),
        ),
    ]
