# Generated by Django 5.1.2 on 2024-11-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0004_alter_obra_funcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='funcion',
        ),
    ]
