# Generated by Django 5.1.2 on 2024-11-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0001_initial'),
        ('obra', '0005_remove_obra_funcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='funcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='funciones.funcion', verbose_name='Obra'),
        ),
    ]
