# Generated by Django 5.1.2 on 2024-11-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0007_remove_obra_fecha_remove_obra_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='funcion',
        ),
    ]
