# Generated by Django 5.1.2 on 2024-11-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0008_remove_obra_funcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
