# Generated by Django 5.1.2 on 2024-11-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_categoria_nombre'),
        ('obra', '0009_obra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria', verbose_name='Categoria'),
        ),
    ]
