# Generated by Django 5.1.1 on 2024-10-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
            },
        ),
    ]
