# Generated by Django 5.1.2 on 2024-12-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='archivo_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
